version: 0.1.0+build.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: Visual Studio 2019
environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
install:
  - cmd: |-
      appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
      rustup-init -yv --default-toolchain %channel% --default-host %target%
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      rustc -vV
      cargo -vV
cache:
  - C:\Users\appveyor\.cargo\bin
  - C:\Users\appveyor\.cargo\.crates2.json
  - C:\Users\appveyor\.cargo\.crates.toml
  - C:\Users\appveyor\.cargo\git
  - C:\Users\appveyor\.cargo\registry\cache
  - C:\Users\appveyor\.cargo\registry\index
  - target
build: off
test_script:
  - pwsh: |-
      Set-ExecutionPolicy Unrestricted -Force
      cargo test --release --all-features --locked
      if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
      }
artifacts:
  - path: target/release/*.exe
