[package]
name = "pkg-license"
version = "0.1.0"
authors = ["AdmiringWorm <kim.nordmo@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
license = "1.1.10"
serde = "1.0.124"
url = { version = "2.2.1", features = ["serde"] }

[dev-dependencies]
rstest = "0.6.4"
